name: Build YR package manually
on:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  package:
    uses: ./.github/workflows/build-bridge.yml
    with:
      artifact_name: YR-MO-DXVK64-Bridge-release
